name: Check
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: leetcode/typescript
      - name: Install deps
        run: pnpm i
      - name: Test
        run: npm run test
